name: Workflow for testing
on: push

env:
  DB_HOST: mariadb
  DB_PORT: 3306
  DB_USER: test
  DB_PASSWORD: test
  DB_NAME: database_test


jobs:

  container-job:
    runs-on: ubuntu-latest
    container: node:12

    services:
      mariadb:
        image: mariadb:10
        env:
          MYSQL_USER: $DB_USER
          # MYSQL_ROOT_PASSWORD is mandatory
          MYSQL_ROOT_PASSWORD: root
          MYSQL_PASSWORD: $DB_PASSWORD
          MYSQL_DATABASE: $DB_NAME

          options: --health-cmd "mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=10

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test