name: Workflow for testing
on: push

env:
  DB_HOST: mariadb
  DB_PORT: 3306
  DB_USER: test
  DB_PASSWORD: test
  DB_NAME: database_test


jobs:

  container-job:
    runs-on: ubuntu-latest
    container: node:12

    services:
      mariadb:
        image: mariadb:10
        env:
          MYSQL_USER: test
          # MYSQL_ROOT_PASSWORD is mandatory
          MYSQL_ROOT_PASSWORD: root
          MYSQL_PASSWORD: test
          MYSQL_DATABASE: database_test

          options: --health-cmd "mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=10

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Wait for container and start tests
        run: npm run test